### ISSUE TITLE
Making the minimal development example to work

### ISSUE THREAD

**Issue by franfran** [LionRockJS/example#1]
To fix a few issues in order to start the 'development' mode.

**Comment by franfran** [comment]
Sorry, just realize you have other branches with the fixes 😅.  So the main branch is not being used and that's why I cannot make it work.
I tried another branch and it is fine.

**Comment by digi3colin** [comment]
I should remove the main branch files and add a readme. 
I'm updating the modules and will do a version bump tonight.

the @lionrockjs/adapter-* repository also use branch for different adapter
eg: 
npm module : @lionrockjs/adapter-mail-aws, for sending email through AWS SES
source repository is lionrockjs/adapter-mail , aws branch.
@lionrockjs/adapter-mail-twilio for sending sms message through Twilio
source repository is lionrockjs/adapter-mail, twilio branch
